### ISSUE TITLE
gzip compression on serving

### ISSUE THREAD

**Issue by steveoc64** [dave/wasmgo#3]
If you are interested, made a quick and dirty fork to add support for gzip compression on `wasmgo serve` without adding any external deps.  Just straight go code.

Is basically adding this file here :

https://github.com/steveoc64/wasmgo/blob/master/cmd/server/compressor.go

and changing 1 line in `cmd/server/server.go` to :

`s := &http.Server{Addr: fmt.Sprintf(":%d", cfg.Port), Handler: compressor(svr.ServeHTTP)}`

Id put in a PR, but it gets messy because of all the re-named include statements :(

**Comment by dave** [comment]
Thanks for this, but I'm not entirely convinced it's needed... `wasmgo serve` is for local testing so you don't really need to compress anything... Is there any use case where this would be useful?

**Comment by steveoc64** [comment]
Yeah, after playing with it for a while and trying to get the whole code-compile-test cycle iterating as fast as possible ... the benefits to gzipping are barely measurable on local, or there are other factors at play which take up way more machine cycles.

Of course, it might be nice if you are doing experimental webasm dev on a remote machine over ssh maybe - but who is going to do that ?

Feel free to close.
